version: '3'

services:
  apt-cacher-ng:
    restart: always
    image: registry.jpconsulted.com/acng/acng:latest
    init: true
    ports:
      - "3142:3142"
    volumes:
      - acng:/acng
      
volumes:
  acng: